//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace JobManagerServiceCore.VerifoneFS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="VerifoneFieldServiceSoap", Namespace="http://www.verifone.com.tr/webservices")]
    public partial class VerifoneFieldService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTerminalInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTerminalInfoWithIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTerminalHistoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTerminalHistoryWithIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTerminalListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTerminalUpdatesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public VerifoneFieldService() {
            this.Url = global::JobManagerServiceCore.Properties.Settings.Default.JobManagerServiceCore_VerifoneFS_VerifoneFieldService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event LogoutCompletedEventHandler LogoutCompleted;
        
        /// <remarks/>
        public event GetTerminalInfoCompletedEventHandler GetTerminalInfoCompleted;
        
        /// <remarks/>
        public event GetTerminalInfoWithIDCompletedEventHandler GetTerminalInfoWithIDCompleted;
        
        /// <remarks/>
        public event GetTerminalHistoryCompletedEventHandler GetTerminalHistoryCompleted;
        
        /// <remarks/>
        public event GetTerminalHistoryWithIDCompletedEventHandler GetTerminalHistoryWithIDCompleted;
        
        /// <remarks/>
        public event GetTerminalListCompletedEventHandler GetTerminalListCompleted;
        
        /// <remarks/>
        public event GetTerminalUpdatesCompletedEventHandler GetTerminalUpdatesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.verifone.com.tr/webservices/Login", RequestNamespace="http://www.verifone.com.tr/webservices", ResponseNamespace="http://www.verifone.com.tr/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSRESULT Login(int fieldSrvID, string username, string password) {
            object[] results = this.Invoke("Login", new object[] {
                        fieldSrvID,
                        username,
                        password});
            return ((WSRESULT)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(int fieldSrvID, string username, string password) {
            this.LoginAsync(fieldSrvID, username, password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(int fieldSrvID, string username, string password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        fieldSrvID,
                        username,
                        password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.verifone.com.tr/webservices/Logout", RequestNamespace="http://www.verifone.com.tr/webservices", ResponseNamespace="http://www.verifone.com.tr/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSRESULT Logout() {
            object[] results = this.Invoke("Logout", new object[0]);
            return ((WSRESULT)(results[0]));
        }
        
        /// <remarks/>
        public void LogoutAsync() {
            this.LogoutAsync(null);
        }
        
        /// <remarks/>
        public void LogoutAsync(object userState) {
            if ((this.LogoutOperationCompleted == null)) {
                this.LogoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogoutOperationCompleted);
            }
            this.InvokeAsync("Logout", new object[0], this.LogoutOperationCompleted, userState);
        }
        
        private void OnLogoutOperationCompleted(object arg) {
            if ((this.LogoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogoutCompleted(this, new LogoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.verifone.com.tr/webservices/GetTerminalInfo", RequestNamespace="http://www.verifone.com.tr/webservices", ResponseNamespace="http://www.verifone.com.tr/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSRESULT GetTerminalInfo(string termSerialNumber) {
            object[] results = this.Invoke("GetTerminalInfo", new object[] {
                        termSerialNumber});
            return ((WSRESULT)(results[0]));
        }
        
        /// <remarks/>
        public void GetTerminalInfoAsync(string termSerialNumber) {
            this.GetTerminalInfoAsync(termSerialNumber, null);
        }
        
        /// <remarks/>
        public void GetTerminalInfoAsync(string termSerialNumber, object userState) {
            if ((this.GetTerminalInfoOperationCompleted == null)) {
                this.GetTerminalInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTerminalInfoOperationCompleted);
            }
            this.InvokeAsync("GetTerminalInfo", new object[] {
                        termSerialNumber}, this.GetTerminalInfoOperationCompleted, userState);
        }
        
        private void OnGetTerminalInfoOperationCompleted(object arg) {
            if ((this.GetTerminalInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTerminalInfoCompleted(this, new GetTerminalInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.verifone.com.tr/webservices/GetTerminalInfoWithID", RequestNamespace="http://www.verifone.com.tr/webservices", ResponseNamespace="http://www.verifone.com.tr/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSRESULT GetTerminalInfoWithID(string okcID) {
            object[] results = this.Invoke("GetTerminalInfoWithID", new object[] {
                        okcID});
            return ((WSRESULT)(results[0]));
        }
        
        /// <remarks/>
        public void GetTerminalInfoWithIDAsync(string okcID) {
            this.GetTerminalInfoWithIDAsync(okcID, null);
        }
        
        /// <remarks/>
        public void GetTerminalInfoWithIDAsync(string okcID, object userState) {
            if ((this.GetTerminalInfoWithIDOperationCompleted == null)) {
                this.GetTerminalInfoWithIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTerminalInfoWithIDOperationCompleted);
            }
            this.InvokeAsync("GetTerminalInfoWithID", new object[] {
                        okcID}, this.GetTerminalInfoWithIDOperationCompleted, userState);
        }
        
        private void OnGetTerminalInfoWithIDOperationCompleted(object arg) {
            if ((this.GetTerminalInfoWithIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTerminalInfoWithIDCompleted(this, new GetTerminalInfoWithIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.verifone.com.tr/webservices/GetTerminalHistory", RequestNamespace="http://www.verifone.com.tr/webservices", ResponseNamespace="http://www.verifone.com.tr/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSRESULT GetTerminalHistory(string termSerialNumber) {
            object[] results = this.Invoke("GetTerminalHistory", new object[] {
                        termSerialNumber});
            return ((WSRESULT)(results[0]));
        }
        
        /// <remarks/>
        public void GetTerminalHistoryAsync(string termSerialNumber) {
            this.GetTerminalHistoryAsync(termSerialNumber, null);
        }
        
        /// <remarks/>
        public void GetTerminalHistoryAsync(string termSerialNumber, object userState) {
            if ((this.GetTerminalHistoryOperationCompleted == null)) {
                this.GetTerminalHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTerminalHistoryOperationCompleted);
            }
            this.InvokeAsync("GetTerminalHistory", new object[] {
                        termSerialNumber}, this.GetTerminalHistoryOperationCompleted, userState);
        }
        
        private void OnGetTerminalHistoryOperationCompleted(object arg) {
            if ((this.GetTerminalHistoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTerminalHistoryCompleted(this, new GetTerminalHistoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.verifone.com.tr/webservices/GetTerminalHistoryWithID", RequestNamespace="http://www.verifone.com.tr/webservices", ResponseNamespace="http://www.verifone.com.tr/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSRESULT GetTerminalHistoryWithID(string okcID) {
            object[] results = this.Invoke("GetTerminalHistoryWithID", new object[] {
                        okcID});
            return ((WSRESULT)(results[0]));
        }
        
        /// <remarks/>
        public void GetTerminalHistoryWithIDAsync(string okcID) {
            this.GetTerminalHistoryWithIDAsync(okcID, null);
        }
        
        /// <remarks/>
        public void GetTerminalHistoryWithIDAsync(string okcID, object userState) {
            if ((this.GetTerminalHistoryWithIDOperationCompleted == null)) {
                this.GetTerminalHistoryWithIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTerminalHistoryWithIDOperationCompleted);
            }
            this.InvokeAsync("GetTerminalHistoryWithID", new object[] {
                        okcID}, this.GetTerminalHistoryWithIDOperationCompleted, userState);
        }
        
        private void OnGetTerminalHistoryWithIDOperationCompleted(object arg) {
            if ((this.GetTerminalHistoryWithIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTerminalHistoryWithIDCompleted(this, new GetTerminalHistoryWithIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.verifone.com.tr/webservices/GetTerminalList", RequestNamespace="http://www.verifone.com.tr/webservices", ResponseNamespace="http://www.verifone.com.tr/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSRESULT GetTerminalList(int startIndex, int terminalCount) {
            object[] results = this.Invoke("GetTerminalList", new object[] {
                        startIndex,
                        terminalCount});
            return ((WSRESULT)(results[0]));
        }
        
        /// <remarks/>
        public void GetTerminalListAsync(int startIndex, int terminalCount) {
            this.GetTerminalListAsync(startIndex, terminalCount, null);
        }
        
        /// <remarks/>
        public void GetTerminalListAsync(int startIndex, int terminalCount, object userState) {
            if ((this.GetTerminalListOperationCompleted == null)) {
                this.GetTerminalListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTerminalListOperationCompleted);
            }
            this.InvokeAsync("GetTerminalList", new object[] {
                        startIndex,
                        terminalCount}, this.GetTerminalListOperationCompleted, userState);
        }
        
        private void OnGetTerminalListOperationCompleted(object arg) {
            if ((this.GetTerminalListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTerminalListCompleted(this, new GetTerminalListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.verifone.com.tr/webservices/GetTerminalUpdates", RequestNamespace="http://www.verifone.com.tr/webservices", ResponseNamespace="http://www.verifone.com.tr/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSRESULT GetTerminalUpdates(System.DateTime dateTime) {
            object[] results = this.Invoke("GetTerminalUpdates", new object[] {
                        dateTime});
            return ((WSRESULT)(results[0]));
        }
        
        /// <remarks/>
        public void GetTerminalUpdatesAsync(System.DateTime dateTime) {
            this.GetTerminalUpdatesAsync(dateTime, null);
        }
        
        /// <remarks/>
        public void GetTerminalUpdatesAsync(System.DateTime dateTime, object userState) {
            if ((this.GetTerminalUpdatesOperationCompleted == null)) {
                this.GetTerminalUpdatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTerminalUpdatesOperationCompleted);
            }
            this.InvokeAsync("GetTerminalUpdates", new object[] {
                        dateTime}, this.GetTerminalUpdatesOperationCompleted, userState);
        }
        
        private void OnGetTerminalUpdatesOperationCompleted(object arg) {
            if ((this.GetTerminalUpdatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTerminalUpdatesCompleted(this, new GetTerminalUpdatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.verifone.com.tr/webservices")]
    public partial class WSRESULT {
        
        private int errCodeField;
        
        private string errDispField;
        
        private string[] resultsField;
        
        /// <remarks/>
        public int errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errDisp {
            get {
                return this.errDispField;
            }
            set {
                this.errDispField = value;
            }
        }
        
        /// <remarks/>
        public string[] results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSRESULT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSRESULT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LogoutCompletedEventHandler(object sender, LogoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSRESULT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSRESULT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTerminalInfoCompletedEventHandler(object sender, GetTerminalInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTerminalInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTerminalInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSRESULT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSRESULT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTerminalInfoWithIDCompletedEventHandler(object sender, GetTerminalInfoWithIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTerminalInfoWithIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTerminalInfoWithIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSRESULT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSRESULT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTerminalHistoryCompletedEventHandler(object sender, GetTerminalHistoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTerminalHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTerminalHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSRESULT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSRESULT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTerminalHistoryWithIDCompletedEventHandler(object sender, GetTerminalHistoryWithIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTerminalHistoryWithIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTerminalHistoryWithIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSRESULT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSRESULT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTerminalListCompletedEventHandler(object sender, GetTerminalListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTerminalListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTerminalListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSRESULT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSRESULT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTerminalUpdatesCompletedEventHandler(object sender, GetTerminalUpdatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTerminalUpdatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTerminalUpdatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSRESULT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSRESULT)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591